language: node_js

node_js:
  - "10.9.0"

cache: yarn

# before_script:
#   - mkdir -p test
#   - cd test/

before_install:
  - npm i -g now

# install:
#   - yarn global add lerna jest

# script:
#   - cd $PACKAGE_LOCATION
#   - yarn test
#   - yarn build

deploy:
  provider: script
  script: now public --token=$NOW_TOKEN
  skip_cleanup: true
  # app: $PACKAGE_NAME