language: node_js

node_js:
  - "10.9.0"

cache: npm

# before_script:
#   - mkdir -p test
#   - cd test/

before_install:
  - npm i -g now

# install:
#   - yarn global add lerna jest

# script:
#   - cd $PACKAGE_LOCATION
#   - yarn test
#   - yarn build

#safelist
branches:
  only:
  - master

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  # app: $PACKAGE_NAME